In [2]:
import pandas as pd

In [3]:
a=1

In [4]:
a = 1

In [5]:
titanic_dataset_github_url_1= "https://raw.githubusercontent.com/datasciencedojo/datasets/refs/heads/master/titanic.csv"

df = pd.read_csv(titanic_dataset_github_url_1)

In [6]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [7]:
# String length 
df['Name'].str.len()

0      23
1      51
2      22
3      44
4      24
       ..
886    21
887    28
888    40
889    21
890    19
Name: Name, Length: 891, dtype: int64

In [8]:
"Shekher".replace("S","SS")

'SShekher'

In [9]:
df['Name_replaced'] = df['Name'].str.replace("Mr.","Sir", regex=False)

In [10]:
df['Name_replaced'].head()

0                              Braund, Sir Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Sir William Henry
Name: Name_replaced, dtype: str

In [11]:
df['Name'].head()

0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
Name: Name, dtype: str

In [12]:
df.loc[1]['Name']

'Cumings, Mrs. John Bradley (Florence Briggs Thayer)'

In [13]:
# another way of doing samething
df.loc[1,'Name']

'Cumings, Mrs. John Bradley (Florence Briggs Thayer)'

In [14]:
start = df.loc[1,'Name'].find("(")

In [15]:
end = df.loc[1,'Name'].find(")")

In [16]:
df.loc[1,'Name'][0:start] + df.loc[1,'Name'][end +1:]

'Cumings, Mrs. John Bradley '

In [17]:
def remove_substring(name):
    start = name.find("(")
    end = name.find(")")
    new_name = name[0:start] + name[end+1:]
    new_name = new_name.strip()
    return new_name

In [18]:
df["Name_trimmed"] =df['Name'].apply(remove_substring)

In [19]:
df["Name_trimmed"].head()

0      Braund, Mr. Owen HarriBraund, Mr. Owen Harris
1                         Cumings, Mrs. John Bradley
2        Heikkinen, Miss. LainHeikkinen, Miss. Laina
3                       Futrelle, Mrs. Jacques Heath
4    Allen, Mr. William HenrAllen, Mr. William Henry
Name: Name_trimmed, dtype: str

## Replace substring with Regex : regular expression

In [20]:
# Replace substring with regex : regular expression
#   * means zero or more
#   . match any charactor 
# "\(.*\)"

# in windows we use \\  double slash
df['Name'].str.replace(r"\(.*\)","HELLO", regex=True).head()

0               Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley HELLO
2                Heikkinen, Miss. Laina
3    Futrelle, Mrs. Jacques Heath HELLO
4              Allen, Mr. William Henry
Name: Name, dtype: str

In [21]:
# in window if we use r strip then with single slash also it works
df['Name'].str.replace("\\(.*\\)","HELLO", regex=True).head()

0               Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley HELLO
2                Heikkinen, Miss. Laina
3    Futrelle, Mrs. Jacques Heath HELLO
4              Allen, Mr. William Henry
Name: Name, dtype: str

# Split and Access Eliments

In [22]:
df['Name'][0]

'Braund, Mr. Owen Harris'

In [23]:
df['Name'].str.split(",")[0]

['Braund', ' Mr. Owen Harris']

In [24]:
df['Name'].str.split().str[0]

0         Braund,
1        Cumings,
2      Heikkinen,
3       Futrelle,
4          Allen,
          ...
886     Montvila,
887       Graham,
888     Johnston,
889         Behr,
890       Dooley,
Name: Name, Length: 891, dtype: object

# Strip Spaces

In [25]:
df['Name'].str.strip()

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: str

In [26]:
df['Name'].str.lstrip()

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: str

In [27]:
df['Name'].str.rstrip()

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: str

# Find Position in Substring

In [28]:
df['Name'].str.find("Mr")

0       8
1       9
2      -1
3      10
4       7
       ..
886    -1
887    -1
888    -1
889     6
890     8
Name: Name, Length: 891, dtype: int64

In [29]:
# Miss
# Count the passengers with "Miss" in the name
Count=df['Name'].str.contains("Miss").sum()
print("Number of 'Miss' in their names:",Count)

Number of 'Miss' in their names: 182

In [31]:
data = {
    'Name':[
        'John Doe','Jane Smith','Emily Jonson',
        'Robert Brown', 'Anna-Marie Lee'
    ],
    'Email':[
        'John@exaple.com','jane.smith@work.org',
        'emily_j@data.net', 'robertb@yahoo.com',
        'anna.lee@company.co'
    ]    

}
df=pd.DataFrame(data)

In [32]:
df.head()

             Name                Email
0        John Doe      John@exaple.com
1      Jane Smith  jane.smith@work.org
2    Emily Jonson     emily_j@data.net
3    Robert Brown    robertb@yahoo.com
4  Anna-Marie Lee  anna.lee@company.co

In [33]:
df['Name'].str.pad(width = 20, side = 'left',fillchar ='-')

0    ------------John Doe
1    ----------Jane Smith
2    --------Emily Jonson
3    --------Robert Brown
4    ------Anna-Marie Lee
Name: Name, dtype: str

In [34]:
df['Name'].str.pad(width = 20, side = 'right',fillchar ='-')

0    John Doe------------
1    Jane Smith----------
2    Emily Jonson--------
3    Robert Brown--------
4    Anna-Marie Lee------
Name: Name, dtype: str

# Categorical Data in Pandas 

## What is Categorical Data ?

### Categorical Data is textual or labeled data that represents discrete cotegories

In [37]:
class_data = {
      "Name":["A","B","C","D"],
     "Groups":["G1","G2","G3","G4"]  
}

In [39]:
class_df = pd.DataFrame(class_data)

In [40]:
class_df.head()

  Name Groups
0    A     G1
1    B     G2
2    C     G3
3    D     G4

In [41]:
class_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      str
 1   Groups  4 non-null      str
dtypes: str(2)
memory usage: 196.0 bytes

In [ ]:
class_df['Group_cat'] = pd.Categorical(
    class_df['Groups'],
    categories =['G3','G1','G2','G4'], # custom order Higher to lower 
    ordered = True
)

In [44]:
class_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Name       4 non-null      str
 1   Groups     4 non-null      str
 2   Group_cat  4 non-null      category
dtypes: category(1), str(2)
memory usage: 404.0 bytes

In [45]:
class_df['Group_cat'].cat.categories

Index(['G3', 'G1', 'G2', 'G4'], dtype='str')

In [46]:
class_df['Groups'] > "G4"

0    False
1    False
2    False
3    False
Name: Groups, dtype: bool